### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by coffeemesh**
Added a small explanatory text for troubleshooting an error message one might receive during a migration.

### CODE REVIEW

**Comment by coffeemesh** [comment]
Relevant [Jira Issue](https://issues.redhat.com/browse/CMTOOL-321)

**Comment by emmartins** [comment]
hi @coffeemesh , can you please point instead to the user guide bundled in the tool zip (at docs directory)? It has a section with the supported migrations.

**Comment by coffeemesh** [comment]
> hi @coffeemesh , can you please point instead to the user guide bundled in the tool zip (at docs directory)? It has a section with the supported migrations.

Hi @emmartins thank you for your feedback. Should I point to the online URL (https://github.com/wildfly/wildfly-server-migration/blob/master/docs/user-guides/tool/standalone/src/main/asciidoc/master.adoc#6-supported-server-migrations) or the local path to the file?

**Comment by coffeemesh** [comment]
@emmartins I know this is nothing big and its kind of dead by now, but if you let me know, I can quickly take care of it or I can just close the PR if something else already fixes this in some other way than the readme.
I haven't used the tool since, but had wanted to share this piece of information which back then was one of the things that held me up

**Comment by emmartins** [comment]
hi @coffeemesh , I will merge it, but may I ask you to squash all as a single commit please?

**Pull request closed without merging**
