### PR TITLE
[CMTOOL-338] added migration of jgroups protocols to EAP8 defaults

### PR DESCRIPTION
**Pull request by istudens**
Issue: https://issues.redhat.com/browse/CMTOOL-338

### CODE REVIEW

**Comment by istudens** [comment]
@emmartins Can you review this please? Thanks

**Comment by OndrejKotek** [comment]
I suggest to also log a warning that the `jgroups` protocols configuration has been changed to match the default one of the target server.

**Comment by emmartins** [comment]
@istudens can you please add a log message as @OndrejKotek suggested, may be similar to what we have for legacy security migrated resources (e.g. https://github.com/emmartins/wildfly-server-migration/blob/47af5f4a8e78e5b53c14c0a62b5564679b544c15/servers/wildfly26.0/src/main/java/org/jboss/migration/wfly/task/security/MigrateLegacySecurityRealmsToElytron.java#L251 )

**Comment by istudens** [comment]
@OndrejKotek @emmartins done

**Review by rhusar — CHANGES_REQUESTED** [review]
This is wrong, see https://issues.redhat.com/browse/CMTOOL-338?focusedId=22387368&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22387368

**Pull request merged**
