### PR TITLE
[CMTOOL-347]  and [CMTOOL-345]

### PR DESCRIPTION
**Pull request by istudens**
Issues:
https://issues.redhat.com/browse/CMTOOL-347
https://issues.redhat.com/browse/CMTOOL-345

### CODE REVIEW

**Comment by istudens** [comment]
@emmartins @okotek can you review this please? thanks

**Comment by OndrejKotek** [comment]
I think this is not sufficient, we should also remove resources depending on Keycloak OIDC adapter modules. The starting point seems to be `custom-realm` and `service-loader-http-server-mechanism-factory` referencing `org.keycloak.keycloak-wildfly-elytron-oidc-adapter` module.

**Comment by OndrejKotek** [comment]
IIUIC there is no new configuration needed. The old subsystem is basically 1-1 copied to the new one, and the new one does not need any additional configuration in form of security domains and realms as it exposes its own virtual security domain. It's matter of application configuration to fit the new server configuration properly.

Hence
- There is no need to refer to "empty subsystem" as the subsystem can be fully configured.
- We should remove all legacy configuration "depending on" legacy OIDC subsystem, as it's not needed and no replacement is needed and it refers modules not present in the new server.
- We should not fail the migration as the new subsystem is supposed to work as expected.

**Comment by OndrejKotek** [comment]
Also I'm OK with this PR as is and we can handle the second part in another one.

**Comment by istudens** [comment]
> Also I'm OK with this PR as is and we can handle the second part in another one.

I agree with this. Can you open a separate PR for it please? Thanks

**Comment by emmartins** [comment]
I have merged this based on @OndrejKotek feedback, and let's use another JIRA for possible enhancements

**Comment by OndrejKotek** [comment]
https://issues.redhat.com/browse/CMTOOL-349 created as follow-up

**Comment by istudens** [comment]
@OndrejKotek thanks for that

**Pull request merged**
