### PR TITLE
[JBEAP-24377] new attribute modules in hibernate cache-container

### PR DESCRIPTION
**Pull request by istudens**
https://issues.redhat.com/browse/CMTOOL-337

### CODE REVIEW

**Comment by istudens** [comment]
This one still needs a migration Jira issue.

**Comment by OndrejKotek** [comment]
@istudens This seems to affect also EAP 8 migrations. Can you update corresponding classes please?

**Comment by istudens** [comment]
@OndrejKotek done

**Comment by parsharma** [comment]
@emmartins could you please review this PR?
Thanks

**Comment by emmartins** [comment]
This was a really nice fix, well done @istudens

**Pull request merged**
