### PR TITLE
[CMTOOL-309] [CMTOOL-322] Legacy Security Migration

### PR DESCRIPTION
**Pull request by emmartins**
Issues: https://issues.redhat.com/browse/CMTOOL-309, https://issues.redhat.com/browse/CMTOOL-322

### CODE REVIEW

**Comment by itiic** [comment]
Hi, are you going complete it?

**Comment by emmartins** [comment]
hi @alex140181 , sorry but no plans for adding migrations to "preview" at the moment, I will soon go back to finish WF25/26 migrations tho.

Honestly the migrations to "preview" should not be much to add, but I guess you still need this first completed and the legacy security migration has turned to be much more complex than I anticipated.

**Comment by dilipkatare** [comment]
@emmartins any idea why when migration tool to wildfly 25 will be available?

**Comment by emmartins** [comment]
there will be more coming on separated PRs, to add support for WFLY 26 and 27, stay tuned

**Pull request merged**
