### PR TITLE
[CMTOOL-352] migrated legacy security domains on datasources and resource-adapters to elytron

### PR DESCRIPTION
**Pull request by istudens**
Issue: https://issues.redhat.com/browse/CMTOOL-352

### CODE REVIEW

**Comment by istudens** [comment]
I still need to test the deployment's resource adapters, I will get back to this once it is done.

**Comment by istudens** [comment]
I am back on this. The `/deployment=name/subsystem=resource-adapter` resource is runtime only and doesn't have any persistent configuration. That was the reason why its migration couldn't work. The current PR no longer includes it.

**Comment by istudens** [comment]
@emmartins Can you review this please? Thanks

**Comment by istudens** [comment]
@emmartins This one still has not been merged. Can you review it please? Thanks

**Comment by emmartins** [comment]
@istudens thanks for the extra notice, I should be able to have a look tomorrow

**Comment by emmartins** [comment]
thank you @istudens

**Pull request merged**
